/**
 * Forge Calendar types.
 *
 * Two flavours of event:
 *   • `UserEvent` — meetings, deadlines, focus blocks, manual entries.
 *   • `SystemEvent` — emitted by Sync (compile windows, patch reviews)
 *     and Pulse (reality-sync runs, decay horizons). System events are
 *     read-only in the UI but ship the same shape so the calendar can
 *     render them on the same grid.
 *
 * Every event carries a `kind` so the renderer can pick the right
 * accent and icon.
 */

export type EventKind =
  | "meeting"
  | "deadline"
  | "focus"
  | "personal"
  // System events — generated by the Compiler.
  | "sync-window"        // recurring Sync compile run
  | "pulse-sync"         // recurring Reality-Sync
  | "decay-horizon"      // when a claim will hit invalidation threshold
  | "patch-review"       // when a proposed patch expires if not actioned
  | "deadline-conflict"; // Sync detected a conflict with this deadline

export type EventSource = "forge" | "google" | "outlook" | "ical";

export interface CalendarEvent {
  id: string;
  /** Project this event belongs to (or "personal"). */
  projectId: string | null;
  title: string;
  /** ISO with timezone offset, OR a date-only string for all-day events. */
  start: string;
  end: string;
  allDay: boolean;
  kind: EventKind;
  /** Optional location ("Zoom", "Loft", URL). */
  location?: string;
  description?: string;
  /** Attendees by display name + optional email. */
  attendees?: { name: string; email?: string }[];
  /** Soft-link back into the workspace (assertion id, doc id, patch id). */
  refs?: { kind: "assertion" | "document" | "patch" | "diff"; id: string }[];
  /** Where the event came from. "forge" = native, "google" etc = imported. */
  source: EventSource;
  /** Optional external id for round-tripping to Google Calendar etc. */
  externalId?: string;
  /** ISO color hint, optional. Renderer ignores when null. */
  colorToken?: "violet" | "cyan" | "warm" | "rose" | "green" | "muted";
  /** Whether this event is editable. System events are not. */
  locked?: boolean;
}

export type CalendarView = "month" | "week" | "day" | "agenda" | "horizon";

export interface CalendarFilter {
  projects: Set<string>;
  kinds: Set<EventKind>;
  sources: Set<EventSource>;
}
